var pointsQueue=[],chunkSize=8;function MapEvent(a,b,c){this.caption=a;this.color=b;this.enabled=c}var mapEvents={def:new MapEvent("customer","#FF2121",!0),mob:new MapEvent("mobile customer","#1AE832",!0),api:new MapEvent("APIs call","#FFFF63",!1)},generalColor="#21E9FF";
L.Control.View=L.Control.extend({options:{position:"bottomright"},onAdd:function(a){var b=L.DomUtil.create("div","leaflet-control-view");this._map=a;this._createButton("View","leaflet-control-view-button",b,this._click,this);return b},_createButton:function(a,b,c,e,d){b=L.DomUtil.create("a",b,c);b.href="#";b.title=a;L.DomEvent.on(b,"click",L.DomEvent.preventDefault).on(b,"click",e,d);L.DomEvent.disableClickPropagation(b);return b},_click:function(a){var b,c;$("#view-dialog").css({right:$(window).width()-
L.DomEvent.getMousePosition(a).x,bottom:$(window).height()-L.DomEvent.getMousePosition(a).y}).mouseleave(function(){b=setTimeout(function(){$("#view-dialog").fadeOut("slow")},500)}).mouseenter(function(){void 0!==b&&clearTimeout(b);void 0!==c&&clearTimeout(c)}).fadeIn("fast");c=setTimeout(function(){$("#view-dialog").fadeOut("slow")},5E3)}});
var pointColor={_all_flag:!1,_add:function(a){void 0!==mapEvents[a]&&(this[a]=this._all_flag?generalColor:mapEvents[a].color)},_rem:function(a){void 0!==this[a]&&delete this[a]},_all:function(){this._all_flag=!0;for(var a in this)void 0!==mapEvents[a]&&(this[a]=generalColor)},_default:function(){this._all_flag=!1;for(var a in this)void 0!==mapEvents[a]&&(this[a]=mapEvents[a].color)}};
function checkHandler(a){"all"==a?$("#all").is(":checked")?pointColor._all():pointColor._default():$("#"+a).is(":checked")?pointColor._add(a):pointColor._rem(a)}function getPseudoGUID(){for(var a=[],b=0;36>b;b++)a[b]="0123456789abcdef".substr(Math.floor(16*Math.random()),1);a[14]="4";a[19]="0123456789abcdef".substr(a[19]&3|8,1);a[8]=a[13]=a[18]=a[23]="-";return a.join("")}
function pt(a,b){if(void 0!==pointColor[a.type]){var c=new R.Pulse(new L.LatLng(a.lat,a.lng),5,{fill:pointColor[a.type],"fill-opacity":0.75,"stroke-opacity":0.75},{fill:pointColor[a.type],"fill-opacity":0.5,"stroke-opacity":0});b.addLayer(c);setTimeout(function(){b.removeLayer(c)},3500)}}function correct(a){var b=L.latLngBounds([-50,-150],[78,179]);a.panTo(b.getCenter());a.setZoom(a.getBoundsZoom(b))}
$(function(){$("#wait").fadeIn("slow");var a=!0,b;for(b in mapEvents)$("#view-dialog").append("<label><input type='checkbox' id='"+b+"'><span style='color: "+mapEvents[b].color+"'>"+mapEvents[b].caption+"</span></label><br>"),$("#"+b).attr("onchange",'checkHandler("'+b+'");'),mapEvents[b].enabled&&(pointColor._add(b),$("#"+b).attr("checked","checked"));$("#view-dialog").append("<hr noshade size='1'><label><input type='checkbox' onchange='checkHandler(\"all\");' id='all' checked='checked'><span style='color: "+
generalColor+"'>one color for all</span></label>");pointColor._all();var c=L.map("map",{zoomControl:!1}).fitWorld();correct(c);$(window).resize(function(){correct(c)});L.tileLayer("http://{s}.tile.cloudmade.com/{key}/{styleId}/256/{z}/{x}/{y}.png",{key:"8d75191ff95943ad89dc5e650d23ffeb",styleId:999,attribution:'Map data by <a href="http://www.ecwid.com/">Ecwid</a>',detectRetina:!0,reuseTiles:!0}).addTo(c);c.addControl(new L.Control.View);(function d(){$.ajax({url:"./get/?id="+getPseudoGUID(),success:function(b){a&&
($("#wait").fadeOut("slow"),a=!1);pointsQueue=pointsQueue.concat(b)},dataType:"json",complete:d,timeout:2E3,cache:!1})})();setInterval(function(){if(pointsQueue.length>=chunkSize)for(var a=pointsQueue.splice(0,chunkSize),b=0;b<chunkSize;b++)pt(a[b],c)},250)});
